version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    tty: true
    environment:
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
